# Generated by Django 3.2.4 on 2021-08-03 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmcommentmodel',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='filmcommentmodel',
            name='unliked',
        ),
        migrations.RemoveField(
            model_name='seriescommentmodel',
            name='liked',
        ),
        migrations.RemoveField(
            model_name='seriescommentmodel',
            name='unliked',
        ),
    ]
