# Generated by Django 3.2.4 on 2021-08-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_auto_20210803_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmcommentmodel',
            name='liked',
            field=models.IntegerField(default=0, verbose_name='liked'),
        ),
        migrations.AddField(
            model_name='filmcommentmodel',
            name='unliked',
            field=models.IntegerField(default=0, verbose_name='unliked'),
        ),
        migrations.AddField(
            model_name='seriescommentmodel',
            name='liked',
            field=models.IntegerField(default=0, verbose_name='liked'),
        ),
        migrations.AddField(
            model_name='seriescommentmodel',
            name='unliked',
            field=models.IntegerField(default=0, verbose_name='unliked'),
        ),
    ]
