# Generated by Django 3.2.4 on 2021-08-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_auto_20210803_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likemodel',
            name='type_like',
        ),
    ]
