# Generated by Django 3.2.4 on 2021-08-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_remove_likemodel_type_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='likemodel',
            name='type_like',
            field=models.IntegerField(default=0, verbose_name='type_like'),
        ),
    ]
