# Generated by Django 3.2.4 on 2021-07-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20210701_0904'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmmodel',
            options={'ordering': ['-pk'], 'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
        migrations.AddField(
            model_name='filmmodel',
            name='IMDb',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='filmseriesmodel',
            name='IMDb',
            field=models.FloatField(default=0),
        ),
    ]
