# Generated by Django 3.2.4 on 2021-07-01 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20210701_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmseriesmodel',
            old_name='category',
            new_name='categoryr',
        ),
    ]
