# Generated by Django 3.2.4 on 2021-07-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_rename_category_filmseriesmodel_categoryr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmseriesmodel',
            old_name='categoryr',
            new_name='category',
        ),
    ]
