# Generated by Django 3.2.4 on 2021-07-01 18:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_rename_categoryr_filmseriesmodel_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmmodel',
            options={'verbose_name': 'film', 'verbose_name_plural': 'films'},
        ),
        migrations.RemoveField(
            model_name='filmseriesmodel',
            name='running_time',
        ),
        migrations.RemoveField(
            model_name='filmseriesvideomodel',
            name='series_number',
        ),
        migrations.AddField(
            model_name='filmseriesseasonmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created_at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='filmseriesvideomodel',
            name='title',
            field=models.CharField(default=2021, max_length=50, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filmseriesvideomodel',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='movie.filmseriesseasonmodel', verbose_name='season'),
        ),
    ]
