# Generated by Django 3.2.4 on 2021-07-07 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_filmseriesvideomodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmseriesvideomodel',
            name='cover',
            field=models.ImageField(default='/static/img/covers/cover.jpg', upload_to='series_cover', verbose_name='cover'),
        ),
        migrations.AlterField(
            model_name='filmseriesvideomodel',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 7, 7), verbose_name='created_at'),
        ),
    ]
