# Generated by Django 3.2.4 on 2021-07-09 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_auto_20210707_1518'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewmodel',
            options={'verbose_name': 'review', 'verbose_name_plural': 'reviews'},
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='title_en',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='filmmodel',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='filmseriesmodel',
            name='title',
            field=models.CharField(db_index=True, max_length=250, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='filmseriesmodel',
            name='title_en',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='filmseriesmodel',
            name='title_ru',
            field=models.CharField(db_index=True, max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='filmseriesvideomodel',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 7, 9), verbose_name='created_at'),
        ),
    ]
