# Generated by Django 3.2.4 on 2021-07-11 17:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0010_auto_20210709_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmseriesvideomodel',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 7, 11), verbose_name='created_at'),
        ),
        migrations.CreateModel(
            name='SeriesCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.filmseriesmodel', verbose_name='series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilmCommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movie.filmmodel', verbose_name='film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='film', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
