# Generated by Django 3.2.4 on 2021-07-13 06:53

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movie', '0012_auto_20210712_1534'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filmcommentmodel',
            options={'verbose_name': 'film_comment', 'verbose_name_plural': 'films_comments'},
        ),
        migrations.AlterModelOptions(
            name='seriescommentmodel',
            options={'verbose_name': 'series_comment', 'verbose_name_plural': 'series_comments'},
        ),
        migrations.AddField(
            model_name='filmcommentmodel',
            name='liked',
            field=models.ManyToManyField(related_name='liked', to=settings.AUTH_USER_MODEL, verbose_name='film_liked'),
        ),
        migrations.AddField(
            model_name='seriescommentmodel',
            name='liked',
            field=models.ManyToManyField(related_name='series_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filmseriesvideomodel',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 7, 13), verbose_name='created_at'),
        ),
        migrations.CreateModel(
            name='LikeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='movie.filmcommentmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'like',
                'verbose_name_plural': 'likes',
            },
        ),
    ]
