# Generated by Django 3.2.4 on 2021-07-19 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0014_auto_20210713_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmseriesvideomodel',
            name='created_at',
            field=models.DateField(default=datetime.date(2021, 7, 19), verbose_name='created_at'),
        ),
    ]
