# Generated by Django 3.2.4 on 2021-08-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0015_alter_filmseriesvideomodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmseriesvideomodel',
            name='created_at',
            field=models.DateField(default=12, verbose_name='created_at'),
        ),
    ]
